title: shumxin's Blog
email: shumxin@sina.com
description: >-
  Quietly Brilliant
baseurl: ""
url: "https://shumxin.github.io"
twitter_username: shumxin
github_username:  shumxin

# Build settings
remote_theme: shumxin/startbootstrap-clean-blog-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme
